### ISSUE TITLE
Curious about the threshold tau selected to conduct experiment

### ISSUE THREAD

**Issue by BirdChristopher** [mit-han-lab/duo-attention#5]
Incredible work! 
It is amazing result that your work successfully prove that "full attention" models can be deployed as "full attention + streaming attention" models with negligible quality loss. I'm curious about how many kv heads are identified as streaming heads when you conducted experiments. Could you please share the number?

**Comment by Guangxuan-Xiao** [comment]
Hi,

The threshold depends on the ratio of streaming heads (sparsity) you plan to use in your experiments. For instance, if you're aiming for 50% streaming heads, the threshold should correspond to the median of the gated values. You can find more details in this section of the code: [duo_attn/utils.py, line 360](https://github.com/mit-han-lab/duo-attention/blob/main/duo_attn/utils.py#L360).

Guangxuan
