### ISSUE TITLE
Codes bug??

### ISSUE THREAD

**Issue by FdyCN** [mit-han-lab/duo-attention#6]
https://github.com/mit-han-lab/duo-attention/blob/0e26e5b5af69e12e720b0aaee8ad7df360f86453/duo_attn/patch/utils.py#L19

full_attention_mask is a torch tensor，How it can be the index？？？

（I did not run the repo, just reviewed these codes.）

**Comment by Guangxuan-Xiao** [comment]
Boolean tensors can be indices.
