### ISSUE TITLE
Question about the figure in paper

### ISSUE THREAD

**Issue by SimonSongg** [mit-han-lab/duo-attention#7]
Hi, thanks for your great work. I am reading your paper and confused a bit about Figure 6.

What does the color in the plot stand for? Are they the attention score accuracy for the attention layer at specific depth and token position?

Thanks.

**Comment by Guangxuan-Xiao** [comment]
This is the accuracy result on the 'Needle in a Haystack' benchmark. For more details, visit: [LLMTest_NeedleInAHaystack](https://github.com/gkamradt/LLMTest_NeedleInAHaystack).

**Comment by SimonSongg** [comment]
> This is the accuracy result on the 'Needle in a Haystack' benchmark. For more details, visit: [LLMTest_NeedleInAHaystack](https://github.com/gkamradt/LLMTest_NeedleInAHaystack).

I see. Thanks for your reply!
