### ISSUE TITLE
Questions about the sparsity

### ISSUE THREAD

**Issue by cyLi-Tiger** [mit-han-lab/duo-attention#8]
Hi, thanks for your great work!

I tried to visualize the sparsity for the models you mentioned in the paper, including other models like Qwen-moe, and have some questions.
![image](https://github.com/user-attachments/assets/56536a60-08de-45c5-b135-67cc0ae2d59f)

1. GQA models generally have lower sparsity than MHA models, especially for Mistral-series and llama3.1. Have you verified the accuracy of duo-attention on those models, since I only find the results for Llama-2-7B-32K-Instruct and Llama-3-8B-Instruct-1048K.
2. The distribution of streaming heads here seems to disobey the insight from papers like [pyramidkv](https://github.com/Zefan-Cai/PyramidKV), which found deeper layers have higher sparsity, cause most of streaming heads of GQA models are found in lower layers.

**Comment by cyLi-Tiger** [comment]
btw, I also noticed that Llama-3-8B-Instruct-1048K suffered obvious loss on some sub benchmarks of Longbench, for example, lsht and vcsum. But other sub benchmarks seem to be lossless, maybe use lower sparsity would recover the precision.
![image](https://github.com/user-attachments/assets/62993333-0f55-4d64-ba41-2c8ef8d3ed9a)

![image](https://github.com/user-attachments/assets/1f939f11-57d2-4176-90e8-a357d2645d78)

**Comment by Guangxuan-Xiao** [comment]
Thank you for your interest in our work and for applying it to additional models! Here are my responses to your questions:

1. Yes, I’ve tested DuoAttention on other GQA models like Mistral and Llama-3.1, and the findings are consistent with those from Llama-3-8B-Instruct-1048K.
2. If I understand correctly, PyramidKV relies on a human-designed heuristic to allocate the KV cache across layers, which is not necessarily the optimal strategy.
3. Indeed, DuoAttention shows more noticeable performance losses on some benchmarks. Reducing sparsity can help mitigate these losses.

**Comment by cyLi-Tiger** [comment]
Got it, thanks!
